import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function getMesAtual(): string {
  const now = new Date();
  return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
}

export const AREAS_PREVIDENCIARIAS = [
  "Aposentadoria por Tempo de Contribuição",
  "Aposentadoria por Invalidez",
  "Aposentadoria por Idade",
  "Benefício de Prestação Continuada (BPC/LOAS)",
  "Auxílio-Doença / Perícia Médica",
  "Pensão por Morte",
  "Salário-Maternidade",
  "Revisão do Teto / Revisão da Vida Toda",
] as const;

export const SUGESTOES_POOL = [
  // Aposentadoria por Tempo de Contribuição
  "Aposentadoria por Tempo de Contribuição: regras antes da reforma",
  "Aposentadoria por Tempo de Contribuição após EC 103/2019",
  "Como calcular o tempo de contribuição para aposentadoria",
  "Tempo de contribuição: o que conta e o que não conta",
  "Trabalho rural conta como tempo de contribuição?",
  "Trabalho informal conta para a aposentadoria?",
  "Contribuição em atraso: como regularizar",
  "CNIS: o que é e como verificar seu histórico",
  "Como corrigir erros no CNIS",
  "Fator previdenciário: como afeta o valor da aposentadoria",
  "Como calcular o valor da aposentadoria",
  "Carência previdenciária: o que é e como calcular",
  "Período de graça: quando você ainda tem direito ao benefício",
  "Contribuição como MEI: como conta para aposentadoria",
  "Contribuição como autônomo: como comprovar",
  "Aposentadoria do trabalhador doméstico: regras e direitos",
  "Como somar tempo de contribuição de dois empregos",
  "Tempo de contribuição militar: como aproveitar no INSS",
  "Acordo internacional de previdência: como usar tempo no exterior",
  "Certidão de Tempo de Contribuição: o que é e quando solicitar",

  // Aposentadoria por Idade
  "Aposentadoria por Idade: requisitos para mulheres (62 anos)",
  "Aposentadoria por Idade: requisitos para homens (65 anos)",
  "Aposentadoria por Idade Rural: regras e documentos",
  "Carência de 180 contribuições para aposentadoria por idade",
  "Aposentadoria por Idade para trabalhador rural: como provar",
  "Como comprovar atividade rural para aposentadoria",
  "Aposentadoria por Idade do MEI: passo a passo",
  "Aposentadoria por Idade do autônomo",
  "Tabela progressiva de idade mínima: regra de transição",
  "Aposentadoria híbrida por idade: misturar rural e urbano",

  // Aposentadoria Especial
  "Aposentadoria Especial: quem tem direito",
  "Aposentadoria Especial: atividades que garantem o benefício",
  "PPP: Perfil Profissiográfico Previdenciário — o que é",
  "LTCAT: Laudo Técnico de Condições Ambientais do Trabalho",
  "Aposentadoria Especial: como provar exposição a agentes nocivos",
  "Agentes químicos que garantem Aposentadoria Especial",
  "Agentes físicos que garantem Aposentadoria Especial",
  "Aposentadoria Especial do técnico em radiologia",
  "Aposentadoria Especial do profissional de saúde",
  "Aposentadoria Especial do motorista de transporte coletivo",
  "Aposentadoria Especial: empresa fechou — como provar",
  "Conversão de tempo especial em tempo comum: como funciona",
  "Aposentadoria Especial após a reforma: o que mudou",
  "EPI elimina a especialidade? O que diz o STJ",
  "Reenquadramento de atividade especial na Justiça",
  "Aposentadoria Especial para quem trabalha com eletricidade",
  "Aposentadoria Especial do trabalhador de mineração",
  "Aposentadoria Especial do vigilante armado",
  "Aposentadoria Especial do trabalhador de frigorífico",
  "Aposentadoria Especial do trabalhador de construção civil",

  // Aposentadoria por Invalidez / Incapacidade Permanente
  "Aposentadoria por Invalidez: requisitos legais",
  "Aposentadoria por Invalidez: como comprovar incapacidade total",
  "Aposentadoria por Invalidez: valor do benefício",
  "Aposentadoria por Invalidez: revisão periódica do INSS",
  "Quando a aposentadoria por invalidez se torna definitiva",
  "Diferença entre Aposentadoria por Invalidez e Auxílio-Doença",
  "Doenças que garantem Aposentadoria por Invalidez sem carência",
  "Aposentadoria por Invalidez acidentária: diferenças",
  "Como recorrer da negativa de Aposentadoria por Invalidez",
  "Benefício por Incapacidade Permanente: nova nomenclatura pós-reforma",

  // Regras de Transição
  "Regras de transição da reforma: qual escolher",
  "Pontos progressivos: como funciona a regra de transição",
  "Pedágio de 50%: para quem se aplica",
  "Pedágio de 100%: para quem se aplica",
  "Aposentadoria antes da reforma: direito adquirido garantido?",
  "Regra de transição de idade progressiva: tabela",
  "Regra de transição tempo de contribuição + idade",
  "Como simular qual regra de transição é mais vantajosa",
  "Pontos da regra de transição: quanto falta para você",
  "Aposentadoria do professor nas regras de transição",

  // Auxílio-Doença / Benefício por Incapacidade Temporária
  "Auxílio-Doença: como solicitar pelo INSS Digital",
  "Auxílio-Doença: documentos obrigatórios",
  "Carência de 12 contribuições para Auxílio-Doença",
  "Quando o Auxílio-Doença não exige carência",
  "Doenças isentas de carência para Auxílio-Doença",
  "Alta programada do INSS: o que é e como contestar",
  "Como prorrogar o Auxílio-Doença",
  "Auxílio-Doença negado: como fazer recurso",
  "Avaliação médico-pericial: seus direitos na perícia",
  "Como se preparar para a perícia médica do INSS",
  "Documentos médicos que o perito aceita",
  "Posso trabalhar durante o Auxílio-Doença?",
  "Auxílio-Doença acidentário: diferenças com o previdenciário",
  "Benefício por Incapacidade Temporária: nova nomenclatura",
  "Monitoramento do benefício: o que esperar",
  "O que acontece se perder a perícia de controle",
  "Incapacidade parcial: direito a reabilitação profissional",
  "Reabilitação Profissional pelo INSS: como funciona",
  "Laudos médicos que convencem o perito do INSS",
  "Quando o médico do INSS difere do médico particular",
  "Carta de concessão do Auxílio-Doença: como interpretar",
  "Auxílio-Doença para trabalhador autônomo",
  "Auxílio-Doença para MEI: carência e valor",
  "Auxílio-Doença para trabalhador doméstico",

  // BPC/LOAS
  "BPC/LOAS para pessoas com deficiência: requisitos",
  "BPC/LOAS para idosos acima de 65 anos",
  "Renda familiar per capita para BPC: como calcular",
  "O que conta como renda da família para o BPC",
  "O que NÃO conta como renda para o cálculo do BPC",
  "BPC negado: como recorrer ao INSS",
  "BPC pode acumular com outros benefícios?",
  "BPC é vitalício?",
  "Como solicitar BPC pelo INSS Digital",
  "Documentos para solicitar BPC/LOAS",
  "Avaliação social para BPC: o papel do assistente social",
  "BPC para pessoa com autismo",
  "BPC para pessoa com deficiência intelectual",
  "BPC para pessoa com deficiência física grave",
  "BPC para pessoa surda",
  "O que acontece se a renda familiar do BPC aumentar",
  "Revisão do BPC: quando e como ocorre",
  "BPC e emprego: posso trabalhar e receber BPC?",
  "Tutela antecipada para BPC: quando é possível",
  "BPC para pessoa com doença rara",
  "BPC para pessoa com câncer",
  "BPC para criança com deficiência",
  "BPC e Benefício de Prestação Continuada: são a mesma coisa?",
  "LOAS: Lei Orgânica da Assistência Social — o que garante",
  "BPC negado na via administrativa: ir à Justiça vale a pena?",

  // Pensão por Morte
  "Pensão por Morte: quem tem direito",
  "Pensão por Morte: como solicitar",
  "Pensão por Morte: documentos necessários",
  "Pensão por Morte: duração do benefício pós-reforma",
  "Cônjuge tem direito à Pensão por Morte?",
  "Companheiro(a) tem direito à Pensão por Morte?",
  "Pensão por Morte para filhos: até que idade",
  "Pensão por Morte para filho inválido: regras",
  "Pais têm direito à Pensão por Morte do filho?",
  "Pensão por Morte: como é calculado o valor",
  "Pensão por Morte após EC 103/2019: o que mudou",
  "Casamento tardio e Pensão por Morte: critérios do INSS",
  "Pensão por Morte acumulável com outros benefícios?",
  "Reversão da Pensão por Morte: quando ocorre",
  "Pensão por Morte para dependente econômico",
  "Como provar dependência econômica para Pensão por Morte",
  "Pensão por Morte negada: como recorrer",
  "Pensão por Morte em casos de desaparecimento",
  "Auxílio-Reclusão vs Pensão por Morte: diferenças",
  "União homoafetiva e Pensão por Morte: o INSS reconhece?",
  "Filho adotado tem direito à Pensão por Morte?",
  "Enteado tem direito à Pensão por Morte?",
  "Pensão por Morte para ex-cônjuge divorciado",
  "Cota parte da Pensão por Morte: como é dividida",
  "Pensão por Morte de servidor público: diferenças",

  // Salário-Maternidade
  "Salário-Maternidade: quem tem direito",
  "Salário-Maternidade para trabalhadora CLT",
  "Salário-Maternidade para MEI",
  "Salário-Maternidade para autônoma",
  "Salário-Maternidade para trabalhadora rural",
  "Carência para Salário-Maternidade",
  "Salário-Maternidade para adoção de criança",
  "Salário-Maternidade para adoção de criança maior",
  "Salário-Maternidade: duração e valor",
  "Salário-Maternidade negado: como recorrer",
  "Parto prematuro e Salário-Maternidade",
  "Natimorto e Salário-Maternidade: há direito?",
  "Aborto espontâneo e Salário-Maternidade",
  "Salário-Maternidade para desempregada",
  "Como o desemprego afeta o Salário-Maternidade",
  "Período de graça e Salário-Maternidade",
  "Salário-Maternidade para trabalhadora doméstica",
  "Salário-Maternidade para pescadora artesanal",
  "Salário-Maternidade: quem paga — empresa ou INSS?",
  "Cálculo do Salário-Maternidade para contribuinte individual",

  // Auxílio-Acidente
  "Auxílio-Acidente: quem tem direito",
  "Auxílio-Acidente: como calcular o valor",
  "Auxílio-Acidente pode acumular com outros benefícios?",
  "Auxílio-Acidente após acidente de trânsito",
  "Diferença entre Auxílio-Acidente e Auxílio-Doença",
  "Auxílio-Acidente e aposentadoria: o que acontece",
  "Nexo causal no Auxílio-Acidente: como provar",
  "CAT: Comunicação de Acidente do Trabalho",
  "Acidente no trajeto: CAT e benefícios",
  "Acidente de trabalho e INSS: benefícios específicos",
  "Doença ocupacional e nexo técnico epidemiológico",
  "NTEP: Nexo Técnico Epidemiológico Previdenciário",

  // Auxílio-Reclusão
  "Auxílio-Reclusão: quem pode receber",
  "Auxílio-Reclusão: valor e duração",
  "Auxílio-Reclusão: renda do segurado para ter direito",
  "Auxílio-Reclusão em regime semiaberto",
  "Auxílio-Reclusão em regime aberto: tem direito?",
  "Como comprovar que o familiar está preso",
  "Auxílio-Reclusão: quando o benefício cessa",
  "Beneficiário saiu da prisão: como reativar o benefício",

  // Revisão de Benefícios
  "Revisão da Vida Toda: o que é e quem tem direito",
  "Revisão da Vida Toda: o que o STF decidiu",
  "Revisão do Teto: quando é possível pedir",
  "Revisão de benefício por erro do INSS",
  "Revisão de aposentadoria calculada com erro",
  "Como pedir revisão de benefício no INSS",
  "Prazo para pedir revisão de benefício: decadência de 10 anos",
  "Revisão do Auxílio-Doença convertido em aposentadoria",
  "Revisão por competências não lançadas no CNIS",
  "Como incluir salários antigos no cálculo do benefício",
  "Atualização monetária no cálculo de benefício",
  "RMI: Renda Mensal Inicial — como é calculada",
  "PBC: Período Básico de Cálculo — o que é",
  "Média dos 80% maiores salários: como funciona",
  "Benefício menor do que o salário mínimo: quando ocorre",
  "Revisão da aposentadoria do servidor convertido para INSS",
  "Tese do marco temporal de contribuições: o que é",

  // Recursos e Processos
  "Indeferimento do INSS: como recorrer",
  "Prazo para recorrer após indeferimento: 30 dias",
  "CRPS: Conselho de Recursos da Previdência Social",
  "Recurso ordinário ao CRPS: como protocolar",
  "Ação judicial contra o INSS: quando vale a pena",
  "Juizado Especial Federal: como entrar com ação contra o INSS",
  "Tutela antecipada em ação previdenciária",
  "Implantação imediata de benefício por decisão judicial",
  "Atrasados do INSS: como calcular os retroativos",
  "RPV: Requisição de Pequeno Valor — como funciona",
  "Precatório do INSS: o que é e como acompanhar",
  "DER: Data de Entrada do Requerimento — sua importância",
  "DIB: Data de Início do Benefício — como é definida",
  "DII: Data de Início da Incapacidade — como provar",
  "Juros e correção monetária nos atrasados do INSS",
  "Prescrição quinquenal em ações previdenciárias",
  "Prova testemunhal em processos previdenciários",
  "Início de prova material em processo previdenciário",
  "Sentença favorável contra o INSS: como cobrar",
  "Cumprimento de sentença previdenciária: passo a passo",
  "Recurso do INSS após sentença favorável ao segurado",
  "Honorários do advogado em ação contra o INSS",
  "Impugnação de laudo pericial no processo previdenciário",
  "Litispendência e coisa julgada em ações previdenciárias",
  "Ação rescisória em matéria previdenciária",

  // Contribuições e Filiação
  "Como se inscrever no INSS como autônomo",
  "Alíquotas de contribuição ao INSS: tabela atualizada",
  "Contribuição facultativa ao INSS: quem pode fazer",
  "Contribuição individual: como regularizar atraso",
  "GPS: Guia de Previdência Social — como emitir",
  "Como pagar INSS retroativo",
  "Recolhimento em atraso: juros e multa",
  "Parcelamento de débito previdenciário",
  "Complementação de contribuição para aumentar benefício",
  "Empresas que não recolheram INSS: o que o segurado pode fazer",
  "Reclamação trabalhista e INSS: como aproveitar",
  "Contribuição sobre 13º salário: como é calculada",
  "Contribuição sobre férias: incide INSS?",
  "Contribuição sobre horas extras",
  "Desoneração da folha e impacto no benefício do trabalhador",

  // Trabalhadores Específicos
  "INSS para trabalhador doméstico: Simples Doméstico",
  "INSS para pescador artesanal: como contribuir",
  "Segurado especial: quem se enquadra",
  "Produtor rural como segurado especial: requisitos",
  "Segurado especial e a carência previdenciária",
  "Garimpeiro e previdência: como contribuir",
  "Indígena e INSS: regras especiais",
  "Médico residente e INSS",
  "Estagiário tem direito a benefícios do INSS?",
  "Aprendiz e INSS: como funciona",
  "Trabalho temporário e INSS",
  "Trabalhador avulso e INSS: regras",
  "Trabalho no exterior: como ficam as contribuições",
  "Microempreendedor Individual: planejamento previdenciário",
  "MEI: como aumentar o salário de contribuição",
  "Trabalhador rural assalariado: direitos previdenciários",
  "Boia-fria e previdência: como comprovar tempo",
  "Cooperado e INSS: como funciona",
  "Clérigo e previdência: regime específico",
  "Artista e INSS: como o contribuinte individual deve contribuir",
  "Motorista de aplicativo e INSS: como se regularizar",
  "Entregador de aplicativo e previdência social",
  "Influenciador digital e INSS: obrigações",
  "Advogado e OAB Prev: diferenças com o INSS",

  // Doenças e Condições Específicas
  "Câncer e benefícios do INSS: o que a lei garante",
  "Parkinson e INSS: quais benefícios são possíveis",
  "Alzheimer e INSS: quais benefícios",
  "HIV/AIDS e benefícios previdenciários",
  "Doença cardíaca grave e aposentadoria por invalidez",
  "Transtorno mental grave e INSS: como comprovar",
  "Depressão grave e afastamento pelo INSS",
  "Artrose avançada e Auxílio-Doença: quando é possível",
  "Hérnia de disco e INSS: como provar incapacidade",
  "LER/DORT e benefícios previdenciários",
  "Sequela pós-acidente e Auxílio-Acidente",
  "Doença rara e BPC: como solicitar",
  "Insuficiência renal crônica e INSS",
  "Lupus e benefícios previdenciários",
  "Fibromialgia e Auxílio-Doença: dificuldades na perícia",
  "Esclerose múltipla e aposentadoria por invalidez",
  "AVC e benefícios: Auxílio-Doença ou aposentadoria?",
  "Diabetes e incapacidade laborativa: quando o INSS paga",
  "Síndrome de Down e BPC",
  "Autismo (TEA) e benefícios do INSS",
  "Deficiência auditiva e BPC",
  "Cegueira e benefícios do INSS",
  "Doença profissional: nexo causal e benefícios",

  // Reforma da Previdência
  "Reforma da Previdência EC 103/2019: o que mudou",
  "O que mudou para quem já contribuía antes da reforma",
  "O que mudou para quem começou a trabalhar após 2019",
  "Como a reforma afetou a Pensão por Morte",
  "Como a reforma afetou o BPC",
  "Reforma e professores: mudanças no direito à aposentadoria",
  "Reforma e Aposentadoria Especial: o que mudou",
  "Reforma e trabalhador rural: impacto nas regras",
  "Abono de Permanência: o que é e quem tem direito",
  "Reforma e fator previdenciário: o que mudou",

  // Planejamento Previdenciário
  "Como planejar a aposentadoria com base na reforma",
  "Quando vale a pena aumentar a contribuição ao INSS",
  "Diferença entre contribuir com 20% e 11% como autônomo",
  "Planejamento previdenciário para empresário",
  "Quando vale a pena antecipar a aposentadoria",
  "Simulação de aposentadoria no Meu INSS: passo a passo",
  "Extrato do CNIS: como interpretar",
  "Meu INSS: como usar o aplicativo",
  "Benefícios que podem ser acumulados pelo mesmo segurado",
  "Prazo legal para o INSS dar resposta ao requerimento",
  "INSS atrasou o pagamento do benefício: o que fazer",
  "Erro no pagamento do benefício: como corrigir",
  "Benefício bloqueado pelo INSS: o que fazer",
  "Benefício suspenso: diferença para benefício cessado",

  // Situações Específicas
  "O que acontece com o INSS em caso de divórcio",
  "Guarda compartilhada e Pensão por Morte",
  "Companheiro informal e Pensão por Morte: como provar",
  "Pessoa presa: perde o benefício do INSS?",
  "Beneficiário falecido: como notificar o INSS",
  "Recebimento indevido de benefício: o que fazer",
  "INSS cobra devolução de valores: seus direitos",
  "Prescrição da dívida com o INSS",
  "Menor de idade pode receber benefício do INSS?",
  "Curatela e tutela para receber benefício previdenciário",
  "Retorno ao trabalho durante Auxílio-Doença",
  "O que acontece se voltar a trabalhar após aposentadoria",
  "Desaposentação: ainda é possível após decisão do STF?",
  "Como o INSS fiscaliza benefícios por incapacidade",
  "Fraude previdenciária: consequências para o segurado",
  "Aposentadoria e IRPF: isenção para doenças graves",
  "Isenção de imposto de renda para aposentado com doença grave",
  "Como solicitar isenção de IR sobre benefício previdenciário",
  "Acordo previdenciário entre Brasil e outros países",
  "Aposentadoria de quem trabalhou no exterior",
  "Como funciona o INSS para brasileiro que voltou do exterior",
  "Pensão alimentícia e INSS: como é descontada",
  "Desconto judicial de benefício: limites legais",
  "Empréstimo consignado em benefício do INSS: limites",
  "Fraude no consignado INSS: como cancelar",
  "Portabilidade do empréstimo consignado INSS",

  // Documentação e Procedimentos
  "Documentos obrigatórios para aposentadoria por tempo de contribuição",
  "Documentos obrigatórios para aposentadoria por idade",
  "Documentos para Auxílio-Doença: lista completa",
  "Como agendar perícia médica no INSS",
  "Como reagendar a perícia do INSS",
  "Atestado médico para o INSS: o que deve conter",
  "Laudo médico vs atestado: diferença para o INSS",
  "Como solicitar benefício sem sair de casa",
  "INSS Digital: como usar para solicitar benefícios",
  "135: central de atendimento do INSS — o que resolve",
  "Carta de exigência do INSS: como responder",
  "Documentos para comprovar trabalho rural",
  "Bloco de notas fiscal do produtor rural como prova",
  "Certidão de casamento como prova de atividade rural",
  "ITR como início de prova material para atividade rural",
  "Como comprovar atividade rural sem documentos",
  "Prova testemunhal para atividade rural: como colher",
  "Homologação do tempo rural: como funciona",

  // Direitos Digitais e Acesso
  "Procuração para representar segurado no INSS",
  "Advogado e acesso ao processo administrativo no INSS",
  "Sigilo médico na perícia do INSS: o que o segurado pode fazer",
  "Gravação da perícia médica pelo segurado: é permitida?",
  "Como acompanhar o andamento do benefício online",
  "Extrato de pagamento do INSS: como verificar",
  "Carta de concessão: como solicitar via postal",
  "Senha do Meu INSS: como recuperar",
  "Biometria no INSS: o que é a prova de vida",
  "Prova de vida INSS: como fazer para quem não pode sair de casa",
  "Prova de vida por procurador: quando é permitida",
  "INSS e LGPD: seus dados previdenciários são protegidos?",

  // Planejamento para Casos Específicos
  "Como a demissão afeta os benefícios do INSS",
  "Demitido sem justa causa: quais benefícios do INSS são mantidos",
  "Pedido de demissão e período de graça do INSS",
  "Licença sem vencimento e INSS: o que acontece",
  "Afastamento por maternidade e tempo de contribuição",
  "Afastamento por acidente e tempo de contribuição",
  "Greve e contribuição ao INSS: o que ocorre",
  "Aposentadoria e rescisão trabalhista: relação",
  "Rescisão indireta e INSS: o trabalhador mantém o benefício?",
  "Falência da empresa e INSS do trabalhador",
  "Recuperação judicial e INSS dos funcionários",

  // Benefícios Acumulados e Vedações
  "Quais benefícios do INSS podem ser acumulados",
  "Vedação de acúmulo: regras gerais",
  "Aposentadoria e Auxílio-Doença: pode acumular?",
  "BPC e outro benefício previdenciário: pode acumular?",
  "Pensão por Morte e aposentadoria: pode acumular?",
  "Dois Auxílios-Doença ao mesmo tempo: é possível?",
  "Acúmulo de benefício de servidor com INSS",

  // Temas Avançados e Jurisprudência
  "Tese do Marco Divisório e benefícios rurais",
  "Aposentadoria especial e retorno ao trabalho insalubre",
  "STJ e INSS: principais súmulas que beneficiam o segurado",
  "STF e INSS: principais decisões favoráveis ao segurado",
  "Revisão da Vida Toda após a decisão do STF: o que fazer",
  "Modulação de efeitos da Revisão da Vida Toda",
  "Tese do Tema 1.102 do STF: impacto nos benefícios",
  "Juros SELIC na correção dos atrasados do INSS",
  "IPCA-E na correção de benefícios: quando se aplica",
  "Inconstitucionalidade do fator previdenciário: como usar",
  "Benefício híbrido rural-urbano: jurisprudência",
  "Comprovação de union estável para fins previdenciários",
  "Reconhecimento de paternidade e Pensão por Morte",
  "Filho maior universitário e Pensão por Morte: tem direito?",
  "Enteado economicamente dependente e Pensão por Morte",
  "Equiparação de filho para fins de Pensão por Morte",
  "Direito adquirido à regra mais benéfica de cálculo",
  "Retroatividade benigna em matéria previdenciária",
  "Princípio da proteção ao hipossuficiente no INSS",
  "Fundamentação insuficiente do indeferimento do INSS",

  // Cálculo e Valores
  "Como calcular a RMI da aposentadoria por tempo de contribuição",
  "Como calcular a RMI da aposentadoria por idade",
  "Salário de contribuição: o que entra no cálculo",
  "Teto do INSS: quanto é e como impacta o benefício",
  "Salário mínimo e benefício previdenciário: relação",
  "Reajuste anual do benefício do INSS: como é calculado",
  "INPC e reajuste de benefícios: entenda o índice",
  "14º salário do aposentado: existe ou é mito?",
  "13º salário de aposentado e pensionista: quando é pago",
  "Benefício previdenciário é tributável pelo IR?",
  "Isenção de IR para aposentado com mais de 65 anos",
  "Dedução do plano de saúde no IR para aposentados",
  "IRPF e benefício do INSS: como declarar corretamente",
  "Imposto retido na fonte pelo INSS: como recuperar",
  "Como declarar atrasados do INSS no imposto de renda",

  // Situações de Transição de Trabalho
  "Aviso prévio e contribuição ao INSS",
  "FGTS e INSS: relação e diferenças",
  "Afastamento e estabilidade de acidente de trabalho",
  "Estabilidade pós-alta do INSS: 12 meses de garantia",
  "Alta do INSS e retorno ao trabalho: o que o empregador pode fazer",
  "Demissão durante Auxílio-Doença: é válida?",
  "Aviso prévio indenizado e benefício do INSS",
  "Verbas rescisórias e contribuição previdenciária",
  "PLR e INSS: incide contribuição?",
  "Auxílio-alimentação e INSS: incide contribuição?",
  "Vale-transporte e contribuição ao INSS",

  // Aposentadoria do Servidor Público
  "RPPS vs RGPS: diferenças entre os regimes previdenciários",
  "Servidor público e aposentadoria pelo INSS: quando é possível",
  "Contagem recíproca de tempo entre INSS e servidor público",
  "CTC: Certidão de Tempo de Contribuição para servidor",
  "Aposentadoria voluntária do servidor federal",
  "Aposentadoria compulsória aos 75 anos do servidor",
  "Pensão por Morte do servidor público: regras pós-reforma",
  "Reforma da Previdência e servidores: o que mudou",
  "Previdência complementar do servidor: FUNPRESP",
  "Servidor estadual e municipal: regimes próprios",

  // Procedimentos no INSS
  "Agendamento no INSS: como fazer pelo Meu INSS",
  "Prazo médio de análise de benefício no INSS",
  "O que fazer quando o INSS demora mais de 45 dias",
  "Mandado de segurança contra demora do INSS",
  "Carta de exigência do INSS: prazo para responder",
  "Como desistir de um benefício solicitado no INSS",
  "Como cancelar voluntariamente um benefício do INSS",
  "INSS Móvel: funcionalidades do aplicativo",
  "Como solicitar a Certidão de Relação de Vínculos",
  "Extrato Previdenciário: como interpretar cada linha",
  "NIT/PIS/PASEP: o que é e para que serve",
  "Como unificar NIT e PIS duplicados no INSS",

  // Proteção ao Segurado
  "Proibição de discriminação por doença no mercado de trabalho",
  "Assédio moral durante afastamento: o trabalhador tem proteção",
  "Retorno ao trabalho e readaptação funcional",
  "Acidente de trabalho: responsabilidade civil do empregador",
  "INSS e responsabilidade do empregador: nexo técnico",
  "Empregador que não recolhe INSS: o que o trabalhador pode fazer",
  "Denúncia de não recolhimento do INSS: como fazer",
  "Débito previdenciário da empresa: impacto no empregado",
  "Reclamação trabalhista como prova de tempo de contribuição",
  "TRCT homologado: quando serve como prova ao INSS",
  "Carteira de Trabalho: como comprovar vínculos empregatícios",
  "CTPS rasgada ou perdida: como substituir para fins previdenciários",
  "Microfilme do PIS/PASEP: como solicitar junto à CEF",

  // Temas Novos e Atuais
  "Inteligência artificial e decisões do INSS: o que mudou",
  "INSS e análise automática de benefícios: riscos",
  "Notificação eletrônica do INSS: como funciona",
  "Domicílio eletrônico trabalhista e INSS",
  "Blockchain e carteira de contribuições: futuro da previdência",
  "Impacto do trabalho intermitente na aposentadoria",
  "Trabalho intermitente e carência previdenciária",
  "Home office e contribuição ao INSS: o que muda",
  "Teletrabalho e acidente de trabalho pelo INSS",
  "Pejotização e risco previdenciário: o que saber",
  "PJ que fica sem renda: pode pedir Auxílio-Doença?",
  "Uberização do trabalho e previdência social",
  "Plataformas digitais e INSS: debate atual",
  "Reforma trabalhista e impactos previdenciários",
  "Contrato verde amarelo e INSS: o que mudou",

  // Casos de Urgência e Tutela
  "Liminar para implantação de benefício: quando é possível",
  "Tutela de urgência em ação previdenciária: requisitos",
  "Antecipação de tutela contra o INSS: jurisprudência",
  "Benefício humanitário em caráter de urgência",
  "Segurado em estado terminal: como acelerar o benefício",
  "Ação de obrigação de fazer contra o INSS",
  "Multa por descumprimento de ordem judicial pelo INSS",
  "Astreintes contra o INSS: aplicação e limites",
  "Como agir quando o INSS perde seu requerimento",
  "Aposentadoria negada por falta de documentos: como resolver",
  "INSS e prova digital: foto, GPS e redes sociais como prova",
  "Perícia judicial vs perícia do INSS: diferenças",
  "Laudo pericial judicial favorável: como usar na via administrativa",
  "Seguro-Desemprego e INSS: como interagem",
  "Contribuição durante Seguro-Desemprego: vale a pena?",
  "Como manter a qualidade de segurado sem emprego formal",
  "Qualidade de segurado: conceito e importância",
  "Perda da qualidade de segurado: como e quando ocorre",
  "Recuperação da qualidade de segurado: como se refiliar",
  "Contribuição mínima para manter qualidade de segurado",
  "Plano Simplificado de Previdência: o que é",
];

export const TONS_CONTEUDO = [
  { valor: "educativo", label: "Educativo", desc: "Explica com clareza e didática" },
  { valor: "empático", label: "Empático", desc: "Conecta com a dor e esperança" },
  { valor: "autoridade", label: "Autoridade", desc: "Postura de especialista confiável" },
  { valor: "prático", label: "Prático", desc: "Direto ao ponto, acionável" },
] as const;

export type AreaPrevidenciaria = (typeof AREAS_PREVIDENCIARIAS)[number];
export type TomConteudo = (typeof TONS_CONTEUDO)[number]["valor"];
export type TipoConteudo = "carrossel" | "reel";
export type StatusConteudo = "ideia" | "revisando" | "agendado" | "publicado";
